#define INPUT_FILE_NAME "input_file.txt"
#define OUTPUT_FILE_NAME "output_file.txt"

#define PREEMPTION_OVERHEAD 0.2
#define DECISION_MAKING_OVERHEAD 0.1
#define FREQUENCY_CALCULATION_OVERHEAD 0.05
#define FREQUENCY_CHANGE_OVERHEAD 0.1